[package]
name = "hadron-pipe-consumer"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[[bin]]
name = "hadron-pipe-consumer"
path = "src/main.rs"

[dependencies]
hadron-syslib = { path = "../hadron-syslib" }
