[package]
name = "hadron-boot-limine"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = [ "hxyulin" ]
license = "GPL-3.0-only"
publish = false

[workspace]

[[bin]]
name = "hadron-boot-limine"
test = false
bench = false
doctest = false

[dependencies]
hadron-drivers = { path = "../../hadron-drivers" }
hadron-kernel = { path = "../../hadron-kernel" }
limine = { path = "../../../crates/boot/limine" }
planck-noalloc = { version = "0.1.1", default-features = false }
