[package]
name = "hadron-boot-limine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "hadron-boot-limine"
test = false
bench = false
doctest = false

[dependencies]
hadron-drivers = { workspace = true }
hadron-kernel = { workspace = true }
limine = { workspace = true }
noalloc = { workspace = true }

[lints]
workspace = true
