[package]
name = "lepton-pipe-test"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[[bin]]
name = "lepton-pipe-test"
path = "src/main.rs"

[dependencies]
lepton-syslib = { path = "../lepton-syslib" }
